# Generated by Django 5.2.8 on 2026-03-04 19:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('people', 'People'), ('vehicle', 'Vehicle'), ('telecom', 'Telecom'), ('location', 'Location')], max_length=20)),
                ('isDeleted', models.BooleanField(default=False)),
                ('source', models.CharField(default='SPACY', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('isManager', models.BooleanField(default=False)),
                ('policeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, choices=[('Constable', 'Constable'), ('Sergeant', 'Sergeant'), ('Inspector', 'Inspector'), ('Chief Inspector', 'Chief Inspector'), ('Superintendent', 'Superintendent'), ('Chief Superintendent', 'Chief Superintendent'), ('Commander', 'Commander'), ('Deputy Assistant Commissioner', 'Deputy Assistant Commissioner'), ('Assistant Commissioner', 'Assistant Commissioner'), ('Deputy Commissioner', 'Deputy Commissioner'), ('Commissioner', 'Commissioner')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EntityProfile',
            fields=[
                ('profileID', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='AI', max_length=10)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='data_processing.entity')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('fullReport', models.TextField()),
                ('intelligenceSource', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isAiGenerated', models.BooleanField(default=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('actionType', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20)),
                ('actionTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_processing.intelligencereport')),
            ],
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('linkID', models.AutoField(primary_key=True, serialize=False)),
                ('relationLevel', models.PositiveSmallIntegerField(blank=True, help_text='Closeness score between the entities, from 1 to 10 (10 is strong relation)', null=True)),
                ('entity1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='data_processing.entity')),
                ('entity2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='data_processing.entity')),
                ('reportLink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_processing.intelligencereport')),
            ],
            options={
                'unique_together': {('entity1', 'entity2', 'reportLink')},
            },
        ),
        migrations.CreateModel(
            name='EntityIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(default=False)),
                ('source', models.CharField(default='SPACY', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing.entity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processing.intelligencereport')),
            ],
            options={
                'unique_together': {('entity', 'report')},
            },
        ),
    ]
