# Generated by Django 5.2.8 on 2025-11-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('fullReport', models.TextField()),
                ('intelligenceSource', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(choices=[('Constable', 'Constable'), ('Sergeant', 'Sergeant'), ('Inspector', 'Inspector'), ('Chief Inspector', 'Chief Inspector'), ('Superintendent', 'Superintendent'), ('Chief Superintendent', 'Chief Superintendent'), ('Commander', 'Commander'), ('Deputy Assistant Commissioner', 'Deputy Assistant Commissioner'), ('Assistant Commissioner', 'Assistant Commissioner'), ('Deputy Commissioner', 'Deputy Commissioner'), ('Commissioner', 'Commissioner')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntityIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.entity')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.intelligencereport')),
            ],
            options={
                'unique_together': {('entity', 'report')},
            },
        ),
    ]
