# Generated by Django 5.2.8 on 2026-01-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('fullReport', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('linkID', models.AutoField(primary_key=True, serialize=False)),
                ('entity_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.entity')),
                ('entity_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_1', to='data_processing.entity')),
                ('intelligence_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.intelligencereport')),
            ],
        ),
        migrations.CreateModel(
            name='EntityIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.entity')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_processing.intelligencereport')),
            ],
            options={
                'unique_together': {('entity', 'report')},
            },
        ),
    ]
